/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_newisys_ova_OVA */

#ifndef _Included_com_newisys_ova_OVA
#define _Included_com_newisys_ova_OVA
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_newisys_ova_OVA
 * Method:    isSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_isSupported
  (JNIEnv *);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    getApiVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_newisys_ova_OVA_getApiVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    registerClient
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_newisys_ova_OVA_registerClient
  (JNIEnv *, jobject);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    setConfigSwitch
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_setConfigSwitch
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    doAction
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_doAction
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    firstAssert
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_newisys_ova_OVA_firstAssert
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    nextAssert
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_newisys_ova_OVA_nextAssert
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    assertDoAction
 * Signature: (JIJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_assertDoAction
  (JNIEnv*, jobject, jlong, jint, jlong, jlong, jlong);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    hasAssertInfo
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_hasAssertInfo
  (JNIEnv*, jobject, jlong);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    getAssertInfo
 * Signature: (JJ)Lcom/newisys/ova/OVAAssertInfo;
 */
JNIEXPORT jobject JNICALL Java_com_newisys_ova_OVA_getAssertInfo
  (JNIEnv*, jobject, jlong, jlong);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    addEngineListener
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_addEngineListener
  (JNIEnv*, jobject, jlong, jint);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    addAssertListener
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_addAssertListener
  (JNIEnv*, jobject, jlong, jint, jlong);


/*
 * Class:     com_newisys_ova_OVA
 * Method:    removeEngineListener
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_removeEngineListener
  (JNIEnv*, jobject, jint);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    removeAssertListener
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_removeAssertListener
  (JNIEnv*, jobject, jint, jlong);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    enableAssertCount
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_enableAssertCount
  (JNIEnv*, jobject, jlong, jlong, jint);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    disableAssertCount
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_disableAssertCount
  (JNIEnv*, jobject, jlong, jlong, jint);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    getAssertCount
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_com_newisys_ova_OVA_getAssertCount
  (JNIEnv*, jobject, jlong, jlong, jint);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    setAssertSeverity
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_setAssertSeverity
  (JNIEnv*, jobject, jlong, jlong, jint);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    getAssertSeverity
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_newisys_ova_OVA_getAssertSeverity
  (JNIEnv*, jobject, jlong, jlong);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    setAssertCategory
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_setAssertCategory
  (JNIEnv*, jobject, jlong, jlong, jint);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    getAssertCategory
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_newisys_ova_OVA_getAssertCategory
  (JNIEnv*, jobject, jlong, jlong);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    setAssertUserMessage
 * Signature: (JJLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_ova_OVA_setAssertUserMessage
  (JNIEnv*, jobject, jlong, jlong, jstring);

/*
 * Class:     com_newisys_ova_OVA
 * Method:    getAssertUserMessage
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_newisys_ova_OVA_getAssertUserMessage
  (JNIEnv*, jobject, jlong, jlong);


#ifdef __cplusplus
}
#endif
#endif
