/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_newisys_verilog_pli_PLI */

#ifndef _Included_com_newisys_verilog_pli_PLI
#define _Included_com_newisys_verilog_pli_PLI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    getInfo
 * Signature: ()Lcom/newisys/verilog/pli/PLIVerilogInfo;
 */
JNIEXPORT jobject JNICALL Java_com_newisys_verilog_pli_PLI_getInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    registerCallback0
 * Signature: (Lcom/newisys/verilog/pli/PLIVerilogCallback;IIJDJI)J
 */
JNIEXPORT jlong JNICALL Java_com_newisys_verilog_pli_PLI_registerCallback0
  (JNIEnv *, jobject, jobject, jint, jint, jlong, jdouble, jlong, jint);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    cancelCallback0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_verilog_pli_PLI_cancelCallback0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    releaseCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_newisys_verilog_pli_PLI_releaseCallback
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    getHandle0
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_com_newisys_verilog_pli_PLI_getHandle0
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    getHandleByName0
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_newisys_verilog_pli_PLI_getHandleByName0
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    getHandleMulti0
 * Signature: (IJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_newisys_verilog_pli_PLI_getHandleMulti0
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    getHandleByIndex0
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_newisys_verilog_pli_PLI_getHandleByIndex0
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    getHandleByMultiIndex0
 * Signature: (J[I)J
 */
JNIEXPORT jlong JNICALL Java_com_newisys_verilog_pli_PLI_getHandleByMultiIndex0
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    iterate0
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_com_newisys_verilog_pli_PLI_iterate0
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    scan0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_newisys_verilog_pli_PLI_scan0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    compareObjects
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_verilog_pli_PLI_compareObjects
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    freeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_newisys_verilog_pli_PLI_freeObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    getPropInt
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_com_newisys_verilog_pli_PLI_getPropInt
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    getPropStr
 * Signature: (IJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_newisys_verilog_pli_PLI_getPropStr
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    getValue0
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_newisys_verilog_pli_PLI_getValue0
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    putValue0
 * Signature: (JLjava/lang/Object;IJDI)J
 */
JNIEXPORT jlong JNICALL Java_com_newisys_verilog_pli_PLI_putValue0
  (JNIEnv *, jobject, jlong, jobject, jint, jlong, jdouble, jint);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    releaseForce0
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_newisys_verilog_pli_PLI_releaseForce0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    getTime
 * Signature: (IJ)Lcom/newisys/verilog/pli/PLITime;
 */
JNIEXPORT jobject JNICALL Java_com_newisys_verilog_pli_PLI_getTime
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    print0
 * Signature: ([BII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_verilog_pli_PLI_print0
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    flush0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_newisys_verilog_pli_PLI_flush0
  (JNIEnv *, jobject);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_newisys_verilog_pli_PLI_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    finish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_newisys_verilog_pli_PLI_finish
  (JNIEnv *, jobject);

/*
 * Class:     com_newisys_verilog_pli_PLI
 * Method:    getError
 * Signature: ()Lcom/newisys/verilog/pli/PLI$ErrorInfo;
 */
JNIEXPORT jobject JNICALL Java_com_newisys_verilog_pli_PLI_getError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
